/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package collegeexamination;

import Project.connectionProvider;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Roshdology
 */
public class CorrectedExam extends javax.swing.JFrame {

    /**
     * Creates new form CorrectedExam
     */
    public CorrectedExam() {
        initComponents();
        showQandA();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ExamName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Question1Text = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Answer1Text = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Question2Text = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Answer2Text = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Question3Text = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Answer3Text = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Question4Text = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Answer4Text = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        gradeNumber = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel1.setText("Exam : ");

        ExamName.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel4.setText("Question 1");

        Question1Text.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        Question1Text.setText("Question Text");

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel6.setText("Answer");

        Answer1Text.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        Answer1Text.setText("Answer Text");

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel8.setText("Question 2");

        Question2Text.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        Question2Text.setText("Question Text");

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel10.setText("Answer");

        Answer2Text.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        Answer2Text.setText("Answer Text");

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel12.setText("Question 3");

        Question3Text.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        Question3Text.setText("Question text");

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel14.setText("Answer");

        Answer3Text.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        Answer3Text.setText("Answer Text ");

        jLabel16.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel16.setText("Question 4");

        Question4Text.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        Question4Text.setText("Question Text");

        jLabel18.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel18.setText("Answer");

        Answer4Text.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        Answer4Text.setText("Answer Text");

        jLabel20.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel20.setText("Your Grade: ");

        gradeNumber.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        gradeNumber.setText("Grade Number");

        jButton1.setBackground(new java.awt.Color(230, 0, 0));
        jButton1.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(34, 34, 34)
                        .addComponent(gradeNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ExamName, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Answer1Text)
                                    .addComponent(Question1Text, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Question2Text))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel14))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Answer3Text)
                                        .addComponent(Question3Text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel16)
                                        .addComponent(jLabel18))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Answer4Text)
                                        .addComponent(Question4Text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(30, 30, 30)
                                .addComponent(Answer2Text, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(ExamName, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Question1Text))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Answer1Text))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Question2Text))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Answer2Text))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Question3Text))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(Answer3Text))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(Question4Text))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(Answer4Text))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(gradeNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LecturerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LecturerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LecturerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LecturerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LecturerForm().setVisible(true);
        });
    }
    private void showQandA()
    {
        try {
            String UserName;
            UserName = Login_Gui.usernameInput.getText();
            String ExamNumber = StudentExam.ExamIDTextField.getText();
            String SubjectName = (String) StudentExam.SubjectComboBox.getSelectedItem();
            ExamName.setText(ExamNumber +" "+ SubjectName);
            Connection c=connectionProvider.getCon();
            Statement st1 = c.createStatement();
            Statement st2 = c.createStatement();
            Statement st3 = c.createStatement();
            Statement st4 = c.createStatement();
            
            Statement st = c.createStatement();
            String sqlQuery = "SELECT * FROM `studentsubjects` WHERE Username ="
                    + " '"+UserName+"' AND SubjectName = '"+SubjectName+"'";
            ResultSet result = st.executeQuery(sqlQuery);
            
            String sqlQuery1 = "select * from exams where ExamNumber = "
                    + "'"+ExamNumber+"' AND QuestionID = 1 AND Subject = '"+SubjectName+"'" ;
            String sqlQuery2 = "select * from exams where ExamNumber = "
                    + "'"+ExamNumber+"'AND QuestionID = 2 AND Subject = "
                    + "'"+SubjectName+"'" ;
            String sqlQuery3 = "select * from exams where ExamNumber = "
                    + "'"+ExamNumber+"' AND QuestionID = 3 AND Subject = '"+SubjectName+"'" ;
            String sqlQuery4 = "select * from exams where ExamNumber = "
                    + "'"+ExamNumber+"'AND QuestionID = 4 AND Subject = '"+SubjectName+"'" ;
            ResultSet result1 = st1.executeQuery(sqlQuery1);
            ResultSet result2 = st2.executeQuery(sqlQuery2);
            ResultSet result3 = st3.executeQuery(sqlQuery3);
            ResultSet result4 = st4.executeQuery(sqlQuery4);
            if(result1.next())
            {
                Question1Text.setText(result1.getString("Question"));
                Answer1Text.setText(result1.getString("Answer"));
            }
            if(result2.next())
            {
                Question2Text.setText(result2.getString("Question"));
                Answer2Text.setText(result2.getString("Answer"));
            }
            if(result3.next())
            {
                Question3Text.setText(result3.getString("Question"));
                Answer3Text.setText(result3.getString("Answer"));
            }
            if(result4.next())
            {
                Question4Text.setText(result4.getString("Question"));
                Answer4Text.setText(result4.getString("Answer"));
            }
            if(result.next())
            {
                gradeNumber.setText(result.getString("ExamGrade"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(CorrectedExam.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Answer1Text;
    private javax.swing.JLabel Answer2Text;
    private javax.swing.JLabel Answer3Text;
    private javax.swing.JLabel Answer4Text;
    private javax.swing.JLabel ExamName;
    private javax.swing.JLabel Question1Text;
    private javax.swing.JLabel Question2Text;
    private javax.swing.JLabel Question3Text;
    private javax.swing.JLabel Question4Text;
    private javax.swing.JLabel gradeNumber;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
