/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package collegeexamination;


import Project.connectionProvider;
import collegeexamination.Login_Gui;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import java.util.*;
import javax.swing.Timer;
import java.awt.event.ActionListener;

/**
 *
 * @author Roshdology
 */
public class ExamForm extends javax.swing.JFrame {

    /**
     * Creates new form ExamForm
     */
    int min = 0;
    int sec = 0;
    public ExamForm() {

        initComponents();
         
        
        int duration = getDuration();
        ButtonGroup1();
        ButtonGroup2();
        ButtonGroup3();
        ButtonGroup4();
        RetreiveQuestions();
        int x = Timerr();
        if(x == duration)
        {
            int marks = validateResult();
            UploadResults(marks);
        }
        
    }
    Timer time;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        QuestionOne = new javax.swing.JLabel();
        QuestionOneOne = new javax.swing.JRadioButton();
        QuestionOneTwo = new javax.swing.JRadioButton();
        QuestionOneFour = new javax.swing.JRadioButton();
        QuestionOneThree = new javax.swing.JRadioButton();
        QuestionTwo = new javax.swing.JLabel();
        QuestionTwoOne = new javax.swing.JRadioButton();
        QuestionTwoTwo = new javax.swing.JRadioButton();
        QuestionTwoFour = new javax.swing.JRadioButton();
        QuestionTwoThree = new javax.swing.JRadioButton();
        QuestionFour = new javax.swing.JLabel();
        QuestionFourOne = new javax.swing.JRadioButton();
        QuestionFourTwo = new javax.swing.JRadioButton();
        QuestionFourFour = new javax.swing.JRadioButton();
        QuestionFourThree = new javax.swing.JRadioButton();
        QuestionThree = new javax.swing.JLabel();
        QuestionThreeOne = new javax.swing.JRadioButton();
        QuestionThreeTwo = new javax.swing.JRadioButton();
        QuestionThreeFour = new javax.swing.JRadioButton();
        QuestionThreeThree = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        examName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Minuits = new javax.swing.JLabel();
        Seconds = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        DurationLabel = new javax.swing.JLabel();
        QuestionNumber = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        QuestionOne.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        QuestionOne.setText("Question TEXT");

        QuestionOneOne.setText("Question 1");
        QuestionOneOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuestionOneOneActionPerformed(evt);
            }
        });

        QuestionOneTwo.setText("Question 2");

        QuestionOneFour.setText("Question 4");
        QuestionOneFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuestionOneFourActionPerformed(evt);
            }
        });

        QuestionOneThree.setText("Question 3");

        QuestionTwo.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        QuestionTwo.setText("Question TEXT");

        QuestionTwoOne.setText("Question 1");
        QuestionTwoOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuestionTwoOneActionPerformed(evt);
            }
        });

        QuestionTwoTwo.setText("Question 2");

        QuestionTwoFour.setText("Question 4");
        QuestionTwoFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuestionTwoFourActionPerformed(evt);
            }
        });

        QuestionTwoThree.setText("Question 3");

        QuestionFour.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        QuestionFour.setText("Question TEXT");

        QuestionFourOne.setText("Question 1");
        QuestionFourOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuestionFourOneActionPerformed(evt);
            }
        });

        QuestionFourTwo.setText("Question 2");

        QuestionFourFour.setText("Question 4");
        QuestionFourFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuestionFourFourActionPerformed(evt);
            }
        });

        QuestionFourThree.setText("Question 3");

        QuestionThree.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        QuestionThree.setText("Question TEXT");

        QuestionThreeOne.setText("Question 1");
        QuestionThreeOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuestionThreeOneActionPerformed(evt);
            }
        });

        QuestionThreeTwo.setText("Question 2");

        QuestionThreeFour.setText("Question 4");
        QuestionThreeFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuestionThreeFourActionPerformed(evt);
            }
        });

        QuestionThreeThree.setText("Question 3");

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        examName.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        examName.setText("Exam Name");

        jLabel1.setText("Time Taken");

        Minuits.setText("00");

        Seconds.setText("00");

        jLabel4.setText("Exam Duration");

        DurationLabel.setText("10 minuits");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(QuestionTwoThree, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(QuestionTwoTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(QuestionTwoOne, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(QuestionTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(QuestionTwoFour, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(QuestionFourThree, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(QuestionFourTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(QuestionFourOne, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(QuestionFour, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(QuestionFourFour, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(QuestionOneThree, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(QuestionOneTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(QuestionOneOne, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(QuestionOne, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(QuestionOneFour, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(QuestionThreeThree, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(QuestionThreeTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(QuestionThreeOne, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(QuestionThree, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(QuestionThreeFour, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(314, 314, 314)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(examName, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(QuestionNumber)
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(Minuits)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Seconds))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DurationLabel)))
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Minuits)
                                    .addComponent(Seconds)
                                    .addComponent(QuestionNumber))
                                .addGap(0, 13, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(DurationLabel))))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(examName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(QuestionThree, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(QuestionThreeOne)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(QuestionThreeTwo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(QuestionThreeThree)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(QuestionThreeFour))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(QuestionOne, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(QuestionOneOne)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(QuestionOneTwo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(QuestionOneThree)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(QuestionOneFour)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(QuestionTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(QuestionTwoOne)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(QuestionTwoTwo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(QuestionTwoThree)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(QuestionTwoFour))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(QuestionFour, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(QuestionFourOne)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(QuestionFourTwo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(QuestionFourThree)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(QuestionFourFour)))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void QuestionOneOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuestionOneOneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuestionOneOneActionPerformed

    private void QuestionOneFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuestionOneFourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuestionOneFourActionPerformed

    private void QuestionTwoOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuestionTwoOneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuestionTwoOneActionPerformed

    private void QuestionTwoFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuestionTwoFourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuestionTwoFourActionPerformed

    private void QuestionFourOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuestionFourOneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuestionFourOneActionPerformed

    private void QuestionFourFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuestionFourFourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuestionFourFourActionPerformed

    private void QuestionThreeOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuestionThreeOneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuestionThreeOneActionPerformed

    private void QuestionThreeFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuestionThreeFourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuestionThreeFourActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int Marks = validateResult();
        UploadResults(Marks);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExamForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExamForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExamForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExamForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ExamForm().setVisible(true);
        });
    }
    public int Timerr()
    {

        int duration = getDuration();
        DurationLabel.setText(duration + " ");
        
                time = new Timer(1000, new ActionListener(){
                    @Override
                    public void actionPerformed(ActionEvent ae){
                    Minuits.setText(Integer.toString(min));
                    Seconds.setText(Integer.toString(sec));
                    if(sec == 60)
                    {
                        
                        sec=0;
                        min++;
                        
                        if(min==duration)
                        {
                            time.stop();
                        }
                    }
                    sec++;
                    
                    }
                });
        time.start();
        return min ;
    }
    private void ButtonGroup1()
    {
        ButtonGroup buttoneGroup1 = new ButtonGroup();
        buttoneGroup1.add(QuestionOneOne);
        buttoneGroup1.add(QuestionOneTwo);
        buttoneGroup1.add(QuestionOneThree);
        buttoneGroup1.add(QuestionOneFour);
    }
    private void ButtonGroup2()
    {
        ButtonGroup buttoneGroup2 = new ButtonGroup();
        buttoneGroup2.add(QuestionTwoOne);
        buttoneGroup2.add(QuestionTwoTwo);
        buttoneGroup2.add(QuestionTwoThree);
        buttoneGroup2.add(QuestionTwoFour);
    }
    private void ButtonGroup3()
    {
        ButtonGroup buttoneGroup3 = new ButtonGroup();
        buttoneGroup3.add(QuestionThreeOne);
        buttoneGroup3.add(QuestionThreeTwo);
        buttoneGroup3.add(QuestionThreeThree);
        buttoneGroup3.add(QuestionThreeFour);
    }
    private void ButtonGroup4()
    {
        ButtonGroup buttoneGroup4 = new ButtonGroup();
        buttoneGroup4.add(QuestionFourOne);
        buttoneGroup4.add(QuestionFourTwo);
        buttoneGroup4.add(QuestionFourThree);
        buttoneGroup4.add(QuestionFourFour);
    }
    private void RetreiveQuestions()
    {
        
        int ExamNumber = Integer.parseInt(StudentExam.ExamIDTextField.getText());
        String SubjectName = (String) StudentExam.SubjectComboBox.getSelectedItem();
      
        try {
            Connection c=connectionProvider.getCon();
            Statement st1 = c.createStatement();
            Statement st2 = c.createStatement();
            Statement st3 = c.createStatement();
            Statement st4 = c.createStatement();
            String sqlQuery1 = "select * from exams where ExamNumber = "
                    + "'"+ExamNumber+"' AND QuestionID = 1 AND Subject = '"+SubjectName+"'" ;
            String sqlQuery2 = "select * from exams where ExamNumber = "
                    + "'"+ExamNumber+"'AND QuestionID = 2 AND Subject = "
                    + "'"+SubjectName+"'" ;
            String sqlQuery3 = "select * from exams where ExamNumber = "
                    + "'"+ExamNumber+"' AND QuestionID = 3 AND Subject = '"+SubjectName+"'" ;
            String sqlQuery4 = "select * from exams where ExamNumber = "
                    + "'"+ExamNumber+"'AND QuestionID = 4 AND Subject = '"+SubjectName+"'" ;
            ResultSet result1 = st1.executeQuery(sqlQuery1);  
            ResultSet result2 = st2.executeQuery(sqlQuery2);
            ResultSet result3 = st3.executeQuery(sqlQuery3);
            ResultSet result4 = st4.executeQuery(sqlQuery4);
            if(result1.next())
            {
                QuestionOne.setText(result1.getString("Question"));
                QuestionOneOne.setText(result1.getString("Option1"));
                QuestionOneTwo.setText(result1.getString("Option2"));
                QuestionOneThree.setText(result1.getString("Option3"));
                QuestionOneFour.setText(result1.getString("Option4"));
            }
            if(result2.next())
            {
                QuestionTwo.setText(result2.getString("Question"));
                QuestionTwoOne.setText(result2.getString("Option1"));
                QuestionTwoTwo.setText(result2.getString("Option2"));
                QuestionTwoThree.setText(result2.getString("Option3"));
                QuestionTwoFour.setText(result2.getString("Option4"));
            }
            if(result3.next())
            {
                QuestionThree.setText(result3.getString("Question")); 
                QuestionThreeOne.setText(result3.getString("Option1"));
                QuestionThreeTwo.setText(result3.getString("Option2"));
                QuestionThreeThree.setText(result3.getString("Option3"));
                QuestionThreeFour.setText(result3.getString("Option4"));
            }
            if(result4.next())
            {
                QuestionFour.setText(result4.getString("Question"));
                QuestionFourOne.setText(result4.getString("Option1"));
                QuestionFourTwo.setText(result4.getString("Option2"));
                QuestionFourThree.setText(result4.getString("Option3"));
                QuestionFourFour.setText(result4.getString("Option4"));
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(ExamForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private int validateResult()
    {
        int Marks= 0;
        try {
            String ExamNumber = StudentExam.ExamIDTextField.getText();
            String SubjectName = (String) StudentExam.SubjectComboBox.getSelectedItem();
            Connection c=connectionProvider.getCon();
            
            Statement st1 = c.createStatement();
            Statement st2 = c.createStatement();
            Statement st3 = c.createStatement();
            Statement st4 = c.createStatement();
            String sqlQuery1 = "select * from exams where ExamNumber ="
                    + " '"+ExamNumber+"' AND QuestionID = '1' AND Subject = '"+SubjectName+"'" ;
            String sqlQuery2 = "select * from exams where ExamNumber ="
                    + " '"+ExamNumber+"' AND QuestionID = '2' AND Subject = '"+SubjectName+"'" ;
            String sqlQuery3 = "select * from exams where ExamNumber ="
                    + " '"+ExamNumber+"' AND QuestionID = '3' AND Subject = '"+SubjectName+"'" ;
            String sqlQuery4 = "select * from exams where ExamNumber ="
                    + " '"+ExamNumber+"' AND QuestionID = '4' AND Subject = '"+SubjectName+"'" ;
            ResultSet result1 = st1.executeQuery(sqlQuery1);
            ResultSet result2 = st2.executeQuery(sqlQuery2);
            ResultSet result3 = st3.executeQuery(sqlQuery3);
            ResultSet result4 = st4.executeQuery(sqlQuery4);
            ButtonGroup buttoneGroup1 = new ButtonGroup();
            buttoneGroup1.add(QuestionOneOne);
            buttoneGroup1.add(QuestionOneTwo);
            buttoneGroup1.add(QuestionOneThree);
            buttoneGroup1.add(QuestionOneFour);
            String Choosen1,Choosen2,Choosen3,Choosen4;
            if(QuestionOneOne.isSelected())
            {
                Choosen1 = QuestionOneOne.getText();
                System.out.println(Choosen1);
            }
            else if(QuestionOneTwo.isSelected())
            {
                Choosen1 = QuestionOneTwo.getText();
                System.out.println(Choosen1);
            }
            else if(QuestionOneThree.isSelected())
            {
                Choosen1 = QuestionOneThree.getText();
                System.out.println(Choosen1);
            }else
            {
                Choosen1 = QuestionOneOne.getText();
                System.out.println(Choosen1);
            }   ButtonGroup buttoneGroup2 = new ButtonGroup();
            buttoneGroup2.add(QuestionTwoOne);
            buttoneGroup2.add(QuestionTwoTwo);
            buttoneGroup2.add(QuestionTwoThree);
            buttoneGroup2.add(QuestionTwoFour);
            if(QuestionTwoOne.isSelected())
            {
                Choosen2 = QuestionTwoOne.getText();
                System.out.println(Choosen2);
            }
            else if(QuestionTwoTwo.isSelected())
            {
                Choosen2 = QuestionTwoTwo.getText();
                System.out.println(Choosen2);
            }
            else if(QuestionTwoThree.isSelected())
            {
                Choosen2 = QuestionTwoThree.getText();
                System.out.println(Choosen2);
            }else
            {
                Choosen2 = QuestionTwoFour.getText();
                System.out.println(Choosen2);
            }   ButtonGroup buttoneGroup3 = new ButtonGroup();
            buttoneGroup3.add(QuestionThreeOne);
            buttoneGroup3.add(QuestionThreeTwo);
            buttoneGroup3.add(QuestionThreeThree);
            buttoneGroup3.add(QuestionThreeFour);
            if(QuestionThreeOne.isSelected())
            {
                Choosen3 = QuestionThreeOne.getText();
                System.out.println(Choosen3);
            }
            else if(QuestionThreeTwo.isSelected())
            {
                Choosen3 = QuestionThreeTwo.getText();
                System.out.println(Choosen3);
            }
            else if(QuestionThreeThree.isSelected())
            {
                Choosen3 = QuestionThreeThree.getText();
                System.out.println(Choosen3);
            }else
            {
                Choosen3 = QuestionThreeFour.getText();
                System.out.println(Choosen3);
            }   ButtonGroup buttoneGroup4 = new ButtonGroup();
            buttoneGroup4.add(QuestionFourOne);
            buttoneGroup4.add(QuestionFourTwo);
            buttoneGroup4.add(QuestionFourThree);
            buttoneGroup4.add(QuestionFourFour);
            if(QuestionFourOne.isSelected())
            {
                Choosen4 = QuestionFourOne.getText();
                System.out.println(Choosen4);
            }
            else if(QuestionFourTwo.isSelected())
            {
                Choosen4 = QuestionFourTwo.getText();
                System.out.println(Choosen4);
            }
            else if(QuestionFourThree.isSelected())
            {
                Choosen4 = QuestionFourThree.getText();
                System.out.println(Choosen4);
            }else
            {
                Choosen4 = QuestionFourFour.getText();
                System.out.println(Choosen4);
            }   // Validation of Answers
            if(result1.next())
            {
                if(Choosen1.equals(result1.getString("Answer")))
                {
                    Marks+=10;
                }
            }
            if(result2.next()){
            if(Choosen2.equals(result2.getString("Answer")))
                {
                    Marks+=10;
                }
            }
            if(result3.next())
            {
            if(Choosen3.equals(result3.getString("Answer")))
                {
                    Marks+=10;
                }
            }
            if(result4.next()){
            if(Choosen4.equals(result4.getString("Answer")))
                {
                    Marks+=10;
                }
            } 
        } catch (SQLException ex) {
            Logger.getLogger(ExamForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return Marks;
        
        
    }
    private void UploadResults(int Marks)
    {
        String username = Login_Gui.usernameInput.getText();
        String ExamNumber = StudentExam.ExamIDTextField.getText();
        String SubjectName = (String) StudentExam.SubjectComboBox.getSelectedItem();
        System.out.println(username + ExamNumber + SubjectName);
        try {
            Connection c=connectionProvider.getCon();
            String sqlQuery = "UPDATE `studentsubjects` SET `ExamGrade`='"+Marks+"'"
                    + ",`NoEntries`='1' WHERE Username = '"+username+"'"
                    + " AND SubjectName = '"+SubjectName+"' AND ExamNumber = "
                    + "'"+ExamNumber+"'";        
            PreparedStatement st = c.prepareStatement(sqlQuery);
            int result = st.executeUpdate(sqlQuery);
            JOptionPane.showMessageDialog(null, "Marks was uploaded to database and"
                    + " you got: "+Marks);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(ExamForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private int getDuration()
    {
        int dur = 0 ;
        try {
            int ExamNumber = Integer.parseInt(StudentExam.ExamIDTextField.getText());
            String SubjectName = (String) StudentExam.SubjectComboBox.getSelectedItem();
            Connection c=connectionProvider.getCon();
            Statement st = c.createStatement();
            String sqlQuery = "select duration from lecturerexamname where examNumber ="
                    + " '"+ExamNumber+"'AND SubjectName = '"+SubjectName+"'";
            ResultSet result = st.executeQuery(sqlQuery);
            if(result.next())
                dur = result.getInt("duration");
        } catch (SQLException ex) {
            Logger.getLogger(ExamForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return dur;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DurationLabel;
    private javax.swing.JLabel Minuits;
    private javax.swing.JLabel QuestionFour;
    private javax.swing.JRadioButton QuestionFourFour;
    private javax.swing.JRadioButton QuestionFourOne;
    private javax.swing.JRadioButton QuestionFourThree;
    private javax.swing.JRadioButton QuestionFourTwo;
    private javax.swing.JLabel QuestionNumber;
    public static javax.swing.JLabel QuestionOne;
    private javax.swing.JRadioButton QuestionOneFour;
    private javax.swing.JRadioButton QuestionOneOne;
    private javax.swing.JRadioButton QuestionOneThree;
    private javax.swing.JRadioButton QuestionOneTwo;
    private javax.swing.JLabel QuestionThree;
    private javax.swing.JRadioButton QuestionThreeFour;
    private javax.swing.JRadioButton QuestionThreeOne;
    private javax.swing.JRadioButton QuestionThreeThree;
    private javax.swing.JRadioButton QuestionThreeTwo;
    private javax.swing.JLabel QuestionTwo;
    private javax.swing.JRadioButton QuestionTwoFour;
    private javax.swing.JRadioButton QuestionTwoOne;
    private javax.swing.JRadioButton QuestionTwoThree;
    private javax.swing.JRadioButton QuestionTwoTwo;
    private javax.swing.JLabel Seconds;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    public static javax.swing.JLabel examName;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
