/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package collegeexamination;

import Project.connectionProvider;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Roshdology
 */
public class TableStudent extends javax.swing.JInternalFrame {

    /**
     * Creates new form TableStudent
     */
    DefaultTableModel tableStudent = new DefaultTableModel();
    public TableStudent() {
        initComponents();
        tableStudent();
        tableStudentContent();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        StudentTable = new javax.swing.JTable();

        StudentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(StudentTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void tableStudent(){
        tableStudent.addColumn("ID");
        tableStudent.addColumn("Username");
        tableStudent.addColumn("Password");
        tableStudent.addColumn("Email");
        tableStudent.addColumn("Fname");
        tableStudent.addColumn("Lname");
        tableStudent.addColumn("GPA");
    }
        private void tableStudentContent(){
            try {
            StudentTable.setModel(tableStudent);
            Connection c=connectionProvider.getCon();
            Statement st = c.createStatement();
            String sqlQuery = "select * from credentials WHERE UserType = 'Student'";
            ResultSet result = st.executeQuery(sqlQuery);
            printTableStudent(result);
        } catch (SQLException ex) {
            Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        private void printTableStudent(ResultSet result){
        try {
            Connection c=connectionProvider.getCon();
            Statement st = c.createStatement();
            tableStudent.setRowCount(0);
            while(result.next())
            {
                tableStudent.addRow(new Object[] {result.getString("ID"),result.getString("Username"),result.getString("Password"),
                    result.getString("Email"),result.getString("Fname")
                        ,result.getString("Lname"),result.getString("Grade")});
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable StudentTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
